-- list of require files to be called from init
require("neo.plugins-setup")
require("neo.core.options")
require("neo.core.keymaps")
require("neo.core.colorscheme")
require("neo.plugins.comment")
require("neo.plugins.nvim-tree")
require("neo.plugins.lualine")
require("neo.plugins.telescope")
require("neo.plugins.nvim-cmp")
require("neo.plugins.lsp.mason")
require("neo.plugins.lsp.lspconfig")
require("neo.plugins.lsp.null-ls")
require("neo.plugins.autopairs")
require("neo.plugins.gitsigns")
